import React from 'react';

export function Disclaimer() {
  return (
    <div
      style={{
        background: '#fff3cd',
        border: '2px solid #ffc107',
        borderRadius: 8,
        padding: '12px 16px',
        marginBottom: 20,
        fontSize: '0.85em',
        lineHeight: 1.5,
      }}
    >
      <strong style={{ color: '#856404' }}>DISCLAIMER:</strong>{' '}
      Factor is an agentic AI research and productivity tool created by A Taylor.
      It does NOT provide legal advice. All analysis is generated by autonomous AI agents
      and may contain errors. The underlying knowledge base is powered by a{' '}
      <strong>synthetic dataset</strong> (Taylor658/synthetic-legal on HuggingFace) —{' '}
      <strong>
        all content including citations, statutes, and case references is artificially
        generated and not legally accurate.
      </strong>{' '}
      Always consult a qualified attorney for legal matters. Use of this tool does not
      create an attorney-client relationship.
    </div>
  );
}
