"""Factor — Agentic AI Legal Due Diligence Platform.

Built with AWS Strands Agents SDK and Amazon Bedrock AgentCore.
Uses Taylor658/synthetic-legal dataset (synthetic, not legally accurate).

Author: A Taylor
"""

__version__ = "0.1.0"
__author__ = "A Taylor"

DISCLAIMER = (
    "DISCLAIMER: Factor is an agentic AI research and productivity tool created by "
    "A Taylor. It does NOT provide legal advice. All analysis is generated by autonomous "
    "AI agents and may contain errors. The underlying knowledge base is powered by a "
    "synthetic dataset (Taylor658/synthetic-legal on HuggingFace) — all content including "
    "citations, statutes, and case references is artificially generated and not legally "
    "accurate. Always consult a qualified attorney for legal matters. Use of this tool "
    "does not create an attorney-client relationship."
)
